apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spiderfoot.fullname" . }}-db
  labels:
    {{- include "spiderfoot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.auth.existingSecret }}
  {}
  {{- else }}
  password: {{ .Values.postgresql.auth.password | default "spiderfoot" | b64enc | quote }}
  {{- end }}
---
{{- if .Values.config.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spiderfoot.fullname" . }}-auth
  labels:
    {{- include "spiderfoot.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.jwtSecret | b64enc | quote }}
{{- end }}
